### ISSUE TITLE
Usage of Wire library.

### ISSUE THREAD

**Issue by Koepel** [ArthurBondar/Underwater-POV-Camera-Tag#1]
In the file "Underwater-POV-Camera-Tag/Version 2/Timing_Software/DS3231.cpp" there is usage of the Wire library that seems odd. I can not make an Issue at https://github.com/rodan/ds3231 because that repository has been archived.

Why is data requested in a while-loop ? 
It is not because the DS3231 is not ready, because that is not in the datasheet.
It would be wrong if it is because the I2C bus is very bad. Requesting data will increase the register address inside the DS3231. If the I2C bus fails, it is impossible to tell if the register address has advanced or not. 
Since setting the register address is not repeated, then why repeat requesting data ?

In the function "DS3231_get_a2()", 4 bytes are requested without using them. It is more straightforward to request data from the right register.

I have made a wiki with an explanation of [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1) and see also my [alternative explanation of the functions of the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library).

**Comment by ArthurBondar** [comment]
Hi @Koepel 
I haven't look into the Wire library in depth, thank you for suggestions. I've modified my functions.

Looks like the current Wire.requestFrom() function doesn't have a timeout option. I found a patch to the underlining twi driver but doesn't look like it made its way into Wire.h
[https://github.com/arduino/Arduino/pull/2489/commits/7dbe76f03f8fe2124e376e8d529dcb79ec2b3e9b#diff-e21536db32c86f5f35e892f4ab6dc2d3](https://github.com/arduino/Arduino/pull/2489/commits/7dbe76f03f8fe2124e376e8d529dcb79ec2b3e9b#diff-e21536db32c86f5f35e892f4ab6dc2d3)

**Comment by Koepel** [comment]
An external event can stop the sketch (shortcut SDA or SCL to GND to to each other). In my opinion that makes the Wire library the worst Arduino library there is.

Many have tried to add a timeout to the official Arduino Wire library, but that is not successful so far. Some use the [WSWire](https://github.com/steamfire/WSWireLib) library. However, that library is not up to date and does not have the newest bug fixes of the Arduino Wire library.

**Comment by ArthurBondar** [comment]
All the more reasons to use Atmel Studio and official drivers...

Luckily for this application, both devices are close to each other on the same PCB, so I don't expect faults on the I2C lines.

Thanks for the tips.
